//This header is generated by CMake, do not edit it. (Changes will be lost)
// Instead edit OpenSpades.h.in, and run CMake again.

#define OpenSpades_VERSION_MAJOR 0
#define OpenSpades_VERSION_MINOR 1
#define OpenSpades_VERSION_REVISION 3

#define OS_STRINGIFY2(x)		#x
#define OS_STRINGIFY(x)			OS_STRINGIFY2(x)

#define OPENSPADES_EXTRATITLE	""
// #define OpenSpades_VER_STR		"OpenSpades " OS_STRINGIFY(OpenSpades_VERSION_MAJOR) "." OS_STRINGIFY(OpenSpades_VERSION_MINOR) "." OS_STRINGIFY(OpenSpades_VERSION_REVISION) OPENSPADES_EXTRATITLE
#define OpenSpades_VER_STR		"# synSpades #"
#define PACKAGE_STRING			OpenSpades_VER_STR

#define OPENSPADES_COMPILER_STR	"GNU 11.2.0"

#define SDL_VERSION_STR			""
#define ZLIB_VERSION_STR		"1.2.11"
#define CURL_VERSION_STR		"7.81.0"

/* #undef RESDIR_DEFINED */
#define RESDIR ""

#define CMAKE_INSTALL_PREFIX "/usr/local"
#define OPENSPADES_INSTALL_RESOURCES "share/games/openspades/Resources"
